version: 2.1

aliases:
  - &restore-cache
    restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
        name: Install dependencies
        command: npm install --legacy-peer-deps
  - &build-packages
    run:
        name: Build
        command: npm run build
  - &run-lint
    run:
        name: Lint
        command: npm run lint

lint-template: &lint-template
  working_directory: ~/Eshopping
  steps:
    - checkout
    - *restore-cache
    - *install-deps
    - *build-packages
    - *run-lint
jobs:
  build:
    working_directory: ~/Eshopping
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Update NPM version
          command: 'sudo npm install -g npm@latest'
      - *restore-cache
      - *install-deps
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - *build-packages

  check-style:
    <<: *lint-template
    docker:
      - image: circleci/node:16
      
workflows:
  version: 2
  build-project:
    jobs:
      - build
      - check-style:
          requires:
            - build